server:
  port: 8088

hbrpc:
  providers: http://localhost:8081/,http://localhost:8082/,http://localhost:8083/
  zkServer: localhost:2181
  zkRootPath: hbrpc

app:
  id: hb
  namespace: public
  env: dev

